version: '3.8'

services:
  # Game Server - WSL Compatible
  game-server:
    build:
      context: .
      dockerfile: Dockerfile.wsl
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - AUTH_SERVER_URL=http://host.docker.internal:3001
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/gamedb?authSource=admin
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - game-network
    # WSL-specific volume mount options
    volumes:
      - type: bind
        source: .
        target: /app/src
        read_only: true

  # MongoDB Database
  mongodb:
    image: mongo:7
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=gamedb
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - game-network

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - game-network

volumes:
  mongodb_data:

networks:
  game-network:
    driver: bridge
